### ISSUE TITLE
匿了

### ISSUE THREAD

**Issue by fridayyue** [chinatimeline/chinatimeline.github.io#1]

**Comment by newjrs** [comment]
![谈什么政治](https://pbs.twimg.com/media/D7OImmpWsAEYXEN?format=jpg&name=900x900)

**Comment by fridayyue** [comment]
你有什么政治主张去可以说的平台，这个平台只是技术分享平台，希望你不要污染它

**Comment by newjrs** [comment]
別誤會，就是特地來嘲諷你一下

**Comment by April-June-August** [comment]
請問那什麼應該和政治扯上關係？你媽？

**Comment by ChengXin** [comment]
interesting. a guy starred 996.icu saying: stay away from politics

**Comment by cirosantilli** [comment]
https://cirosantilli.com/china-dictatorship/#meant-to-be-used
