### ISSUE TITLE
用离线版RSS阅读器看新闻-顺便提交新闻内容至时代透镜

### ISSUE THREAD

**Issue by NodeBE4** [chinatimeline/chinatimeline.github.io#111]
网页项目 
https://github.com/NodeBE4/news
访问地址
https://nodebe4.github.io/news/

注意右上角大大的 **提交至时代透镜** 的按钮，enjoy

欢迎fork

**Comment by chinatimeline** [comment]
工具很强大，请问是否方便提供js源代码而不是mini部署版？
